import { projects } from "@/data/projects";

const base = `${process.env.NEXT_PUBLIC_BASE_PATH ?? ""}/projects/fpa`;

// Content supplied by Jehu, verified resume context, and the supplied FPA walkthrough.
export const fpaProject = {
  id: "fpa-chapter",
  name: projects[0].name,
  category: "Government Systems",
  summary: "Digitizing leave workflows, document routing, and leave-credit calculation through responsive interfaces.",
  technologies: ["PHP", "JavaScript", "MySQL", "Workflow Automation", "UAT"],
  workflow: ["Employee", "HR Certification", "Supervisor", "Final Approval"],
  video: `${base}/fpa-teaser.mp4`,
  poster: `${base}/fpa-poster.webp`,
  recognition: {
    label: "View FPA recognition",
    url: "https://www.facebook.com/share/p/1CXjfhPa7G/",
    source: "Facebook",
  },
  finale: "From leave request to approval, official document generation, and leave-credit records.",
  beats: [
    { id: "intro", label: "The system", title: "A digital leave workflow.", copy: "A walkthrough of leave filing, document routing, and approval.", image: null, alt: null },
    { id: "workflow", label: "Application tracking", title: "One request. A clear path.", copy: "Document routing connects the employee, HR certification, supervisor, and final approval.", image: `${base}/application-tracking.webp`, alt: "FPA application details showing leave-credit balance preview and the HR, supervisor, and final approval stages." },
    { id: "document", label: "CSC Form No. 6", title: "From approval to official document.", copy: "The leave workflow produces the official CSC Form No. 6, connecting the application and its approval record.", image: `${base}/csc-form-approved.webp`, alt: "Official CSC Form No. 6 generated by FPA Leave Management System, with application details, leave-credit certification, and approval information." },
    { id: "ledger", label: "Leave Credit Ledger", title: "The record continues.", copy: "The system also maintains leave-credit records and balances, supported by leave-credit calculation.", image: `${base}/leave-credit-ledger.webp`, alt: "FPA Leave Credit Ledger interface showing leave-credit records and balances." },
  ],
} as const;
